### ISSUE TITLE
the other

### ISSUE THREAD

**Issue by hectorsector** [cop1000/scratch#2]

**Comment by halfaro1-teststudent** [comment]
hi

**Comment by halfaro1-teststudent** [comment]
and now?

**Comment by hectorsector** [comment]
:tada: @halfaro1-teststudent is now a repository collaborator. :balloon:

**Comment by halfaro1-teststudent** [comment]
awesome!

**Comment by hectorsector** [comment]
Great work!

**Comment by halfaro1-teststudent** [comment]
here's a test

**Comment by halfaro1-teststudent** [comment]
another one?

**Comment by halfaro1-teststudent** [comment]
testing!

**Comment by halfaro1-teststudent** [comment]
hi

**Comment by halfaro1-teststudent** [comment]
testing

**Comment by halfaro1-teststudent** [comment]
this should be ignored

**Comment by hectorsector** [comment]
:tada: @halfaro1-teststudent, @halfaro1-teststudent, @halfaro1-teststudent, @halfaro1-teststudent, @halfaro1-teststudent, @halfaro1-teststudent, @halfaro1-teststudent, @halfaro1-teststudent, and @halfaro1-teststudent are now  repository collaborators. :balloon:

**Comment by hectorsector** [comment]
:tada: @halfaro1-teststudent, @halfaro1-teststudent, @halfaro1-teststudent, @halfaro1-teststudent, @halfaro1-teststudent, @halfaro1-teststudent, @halfaro1-teststudent, @halfaro1-teststudent, and @halfaro1-teststudent are now  repository collaborators. :balloon:

**Comment by hectorsector** [comment]
:tada: @halfaro1-teststudent, @halfaro1-teststudent, @halfaro1-teststudent, @halfaro1-teststudent, @halfaro1-teststudent, @halfaro1-teststudent, @halfaro1-teststudent, @halfaro1-teststudent, and @halfaro1-teststudent are now  repository collaborators. :balloon:

**Comment by hectorsector** [comment]
:tada: @halfaro1-teststudent, @halfaro1-teststudent, @halfaro1-teststudent, @halfaro1-teststudent, @halfaro1-teststudent, @halfaro1-teststudent, @halfaro1-teststudent, @halfaro1-teststudent, and @halfaro1-teststudent are now  repository collaborators. :balloon:

**Comment by hectorsector** [comment]
:tada: @halfaro1-teststudent, @halfaro1-teststudent, @halfaro1-teststudent, @halfaro1-teststudent, @halfaro1-teststudent, @halfaro1-teststudent, @halfaro1-teststudent, @halfaro1-teststudent, and @halfaro1-teststudent are now  repository collaborators. :balloon:

**Comment by hectorsector** [comment]
:tada: @halfaro1-teststudent, @halfaro1-teststudent, @halfaro1-teststudent, @halfaro1-teststudent, @halfaro1-teststudent, @halfaro1-teststudent, @halfaro1-teststudent, @halfaro1-teststudent, and @halfaro1-teststudent are now  repository collaborators. :balloon:

**Comment by hectorsector** [comment]
:tada: @halfaro1-teststudent, @halfaro1-teststudent, @halfaro1-teststudent, @halfaro1-teststudent, @halfaro1-teststudent, @halfaro1-teststudent, @halfaro1-teststudent, @halfaro1-teststudent, and @halfaro1-teststudent are now  repository collaborators. :balloon:

**Comment by hectorsector** [comment]
:tada: @halfaro1-teststudent, @halfaro1-teststudent, @halfaro1-teststudent, @halfaro1-teststudent, @halfaro1-teststudent, @halfaro1-teststudent, @halfaro1-teststudent, @halfaro1-teststudent, and @halfaro1-teststudent are now  repository collaborators. :balloon:

**Comment by halfaro1-teststudent** [comment]
hi

**Comment by halfaro1-teststudent** [comment]
hello

**Comment by halfaro1-teststudent** [comment]
hi there!

**Comment by halfaro1-teststudent** [comment]
another test?

**Comment by halfaro1-teststudent** [comment]
testing

**Comment by halfaro1-teststudent** [comment]
another?

**Comment by halfaro1-teststudent** [comment]
hi

**Comment by hectorsector** [comment]
:tada: @halfaro1-teststudent is now a repository collaborator. :balloon:

**Comment by halfaro1-teststudent** [comment]
testing

**Comment by halfaro1-teststudent** [comment]
hi

**Comment by hectorsector** [comment]
another test?

**Comment by halfaro1-teststudent** [comment]
should be ignored
